image: "alpine"
stages:
  - build
  - publish

cache:
  paths:
    - build/libs/

build:
  image: openjdk:8
  stage: build
  script:
    - ./gradlew build

publish:
  image: alpine
  stage: publish
  only:
    - tags
  before_script:
    - apk update
    - apk add git zip
  script:
    - export VERSION=`git describe --tags --dirty`
    - cp build/libs/mangadex_at_home-${VERSION}-all.jar ./
    - zip -r9 mangadex_at_home-${VERSION}.zip mangadex_at_home-${VERSION}-all.jar settings.sample.json
  artifacts:
    name: "mangadex_at_home-${CI_COMMIT_TAG}"
    paths:
      - "*.jar"
      - settings.sample.json
